# Generated by Django 4.1.4 on 2022-12-29 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, null=True)),
                ('phone_number', models.IntegerField(help_text='Enter your Phone number')),
                ('type_of_incident', models.CharField(choices=[('SCH', 'Sewer_Choke'), ('MANC', 'Manhole_Clog'), ('SPBU', 'Sewer_Pipe_Burst'), ('SPCL', 'Sewer_Pipe_Clog'), ('MANB', 'Manhole_Burst'), ('SPLE', 'Sewer_Pipe_Leakage'), ('OSF', 'Open_Sewage_Flowing')], max_length=100)),
                ('images', models.ImageField(upload_to='')),
                ('description', models.TextField(blank=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Repo.location')),
            ],
        ),
    ]
