# Generated by Django 4.2.dev20220930042619 on 2023-02-16 12:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='images',
            field=models.FileField(null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326, verbose_name='location'),
        ),
    ]
