# Generated by Django 4.2.dev20220930042619 on 2023-02-24 07:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Repo', '0002_alter_report_images_alter_report_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name_plural': 'Sewer incidents'},
        ),
        migrations.AddField(
            model_name='report',
            name='date_reported',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date reported'),
        ),
    ]
