# Generated by Django 4.2.dev20220930042619 on 2023-02-24 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repo', '0003_alter_report_options_report_date_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='date_occurred',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_reported',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date reported'),
        ),
    ]
