# Generated by Django 4.2.dev20220930042619 on 2023-02-24 07:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Repo', '0005_alter_report_date_reported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_reported',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Reported'),
        ),
    ]
