# Generated by Django 4.2.dev20220930042619 on 2023-02-26 17:13

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Repo', '0006_alter_report_date_reported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326, verbose_name='location'),
        ),
    ]
