# Generated by Django 4.2.dev20220930042619 on 2023-02-27 07:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repo', '0007_alter_report_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='resolved_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='report',
            name='type_of_incident',
            field=models.CharField(choices=[('Sewer_Choke', 'Sewer_Choke'), ('Manhole_Clog', 'Manhole_Clog'), ('Sewer_Pipe_Burst', 'Sewer_Pipe_Burst'), ('Sewer_Pipe_Clog', 'Sewer_Pipe_Clog'), ('Manhole_Burst', 'Manhole_Burst'), ('Sewer_Pipe Leakage', 'Sewer_Pipe_Leakage'), ('Open_Sewage_Flowing', 'Open_Sewage_Flowing'), ('Oduor', 'Oduor'), ('Any_Other_Kind', 'Any_Other_Kind')], max_length=100),
        ),
    ]
