# Generated by Django 4.2.dev20220930042619 on 2023-02-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repo', '0010_report_is_resolved_alter_report_type_of_incident'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='is_resolved',
        ),
        migrations.AlterField(
            model_name='report',
            name='type_of_incident',
            field=models.CharField(choices=[('SCH', 'Sewer_Choke'), ('MANC', 'Manhole_Clog'), ('SPBU', 'Sewer_Pipe_Burst'), ('SPCL', 'Sewer_Pipe_Clog'), ('MANB', 'Manhole_Burst'), ('SPLE', 'Sewer_Pipe_Leakage'), ('OSF', 'Open_Sewage_Flowing'), ('OTR', 'Any_Other_Kind')], max_length=100),
        ),
    ]
