# Generated by Django 4.2.dev20220930042619 on 2023-02-27 11:35

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Repo', '0012_report_is_resolved_report_resolved_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=None, null=True, srid=4326, verbose_name='Location'),
        ),
        
    ]
    operations = [ 
        migrations.RunSQL( "ALTER TABLE Sewer_Repo_Track_2 ALTER COLUMN location TYPE geometry(Point,4326) USING ST_SetSRID(location::geometry, 4326);")
                  ]