# Generated by Django 4.2.dev20220930042619 on 2023-02-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repo', '0014_alter_report_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='Location'),
        ),
    ]
