# Generated by Django 4.2.dev20220930042619 on 2023-02-27 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Repo', '0015_alter_report_location'),
    ]

    operations = [
    migrations.RunSQL('ALTER TABLE Repo_report ALTER COLUMN location TYPE geometry(Point,4326) USING location::geometry(Point,4326);'),

    ]
