# Generated by Django 4.2.dev20220930042619 on 2023-02-27 12:44

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Repo', '0016_auto_20230227_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='is_resolved',
        ),
        migrations.RemoveField(
            model_name='report',
            name='resolved_on',
        ),
        migrations.AlterField(
            model_name='report',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326, verbose_name='location'),
        ),
    ]
